### ISSUE TITLE
Can't locate Collectd/Plugins/NetApp/FlashCache.pm

### ISSUE THREAD

**Issue by scebryan** [aleex42/Collectd-Plugins-NetApp#8]
Hi guys,

In the file NetApp.pm, line 26, invokes the next lib:
use Collectd::Plugins::NetApp::FlashCache qw(flashcache_module);

But the FlashCache.pm file is not in the folder.
Could you upload it or is it in development?

Thanks!!
Regards.

**Comment by aleex42** [comment]
Thanks for the hint, I've missed the "git add" :-)

Is fixed!
